# Generated by Django 3.2.5 on 2024-07-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('login_id', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('fst_mail', models.CharField(blank=True, max_length=400, null=True)),
                ('mail_img', models.CharField(blank=True, max_length=100, null=True)),
                ('post_title', models.CharField(blank=True, max_length=40, null=True)),
                ('post_content', models.CharField(blank=True, max_length=500, null=True)),
                ('second_message', models.CharField(blank=True, max_length=400, null=True)),
                ('condition_message', models.CharField(blank=True, max_length=400, null=True)),
                ('return_foot_message', models.CharField(max_length=400)),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('self_promotion', models.CharField(blank=True, max_length=500, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body_shape', models.CharField(choices=[('未設定', '未設定'), ('スリム', 'スリム'), ('やや細め', 'やや細め'), ('グラマー', 'グラマー'), ('ややぽっちゃり', 'ややぽっちゃり'), ('太め', '太め')], max_length=20)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('秘密', '秘密')], max_length=5)),
                ('activity_area', models.CharField(choices=[('東京都', '東京都')], max_length=5)),
                ('detail_activity_area', models.CharField(blank=True, max_length=10, null=True)),
                ('profession', models.CharField(blank=True, max_length=20, null=True)),
                ('freetime', models.CharField(choices=[('不規則で決まってない', '不規則で決まってない'), ('秘密', '秘密'), ('平日の昼間', '平日の昼間'), ('平日の夜', '平日の夜')], max_length=20)),
                ('car_ownership', models.CharField(choices=[('ない', 'ない')], max_length=20)),
                ('smoking', models.CharField(choices=[('吸わない(喫煙は気にしない)', '吸わない(喫煙は気にしない)')], max_length=20)),
                ('ecchiness_level', models.CharField(choices=[('積極的で好奇心旺盛', '積極的で好奇心旺盛'), ('普通だけど刺激が欲しい', '普通だけど刺激が欲しい'), ('普通だけど相性は大事', '普通だけど相性は大事')], max_length=20)),
                ('sake', models.CharField(choices=[('たしなむ程度', 'たしなむ程度'), ('飲めない', '飲めない'), ('飲めないが場は好き', '飲めないが場は好き')], max_length=20)),
                ('process_before_meeting', models.CharField(choices=[('まずは会ってみたい', 'まずは会ってみたい'), ('気が合いそうなら会ってみたい', '気が合いそうなら会ってみたい')], max_length=20)),
                ('first_date_cost', models.CharField(choices=[('相手と相談して決める', '相手と相談して決める')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pcmax',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Happymail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('login_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fst_message', models.TextField()),
                ('return_foot_message', models.TextField()),
                ('conditions_message', models.TextField()),
                ('post_title', models.TextField()),
                ('post_contents', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'happymail',
                'managed': True,
            },
        ),
    ]
