# Generated by Django 5.1 on 2024-08-31 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Happymail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名前')),
                ('login_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ログインID')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='パスワード')),
                ('fst_message', models.TextField(blank=True, null=True, verbose_name='1stメール')),
                ('return_foot_message', models.TextField(blank=True, null=True, verbose_name='足跡返し')),
                ('conditions_message', models.TextField(blank=True, null=True, verbose_name='2stメール')),
                ('post_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='掲示板タイトル')),
                ('post_contents', models.TextField(blank=True, null=True, verbose_name='掲示板内容文')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ハッピーメール',
                'verbose_name_plural': 'ハッピーメール',
                'db_table': 'happymail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pcmax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名前')),
                ('login_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ログインID')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='パスワード')),
                ('fst_mail', models.TextField(blank=True, null=True, verbose_name='1stメール')),
                ('mail_img', models.CharField(blank=True, max_length=100, null=True)),
                ('post_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='掲示板タイトル')),
                ('post_content', models.TextField(blank=True, null=True, verbose_name='掲示板内容文')),
                ('second_message', models.TextField(blank=True, null=True)),
                ('condition_message', models.TextField(blank=True, null=True)),
                ('return_foot_message', models.TextField(blank=True, null=True, verbose_name='足跡返し')),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('self_promotion', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('普通', '普通'), ('未設定', '未設定'), ('スリム', 'スリム'), ('やや細め', 'やや細め'), ('グラマー', 'グラマー'), ('ややぽっちゃり', 'ややぽっちゃり'), ('太め', '太め')], max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('秘密', '秘密')], max_length=5, null=True)),
                ('activity_area', models.CharField(blank=True, choices=[('東京都', '東京都')], max_length=5, null=True)),
                ('detail_activity_area', models.CharField(blank=True, max_length=10, null=True)),
                ('profession', models.TextField(blank=True, null=True)),
                ('freetime', models.CharField(blank=True, choices=[('不規則で決まってない', '不規則で決まってない'), ('秘密', '秘密'), ('平日の昼間', '平日の昼間'), ('平日の夜', '平日の夜')], max_length=20, null=True)),
                ('car_ownership', models.CharField(blank=True, choices=[('ない', 'ない')], max_length=20, null=True)),
                ('smoking', models.CharField(blank=True, choices=[('吸わない(喫煙は気にしない)', '吸わない(喫煙は気にしない)')], max_length=20, null=True)),
                ('ecchiness_level', models.CharField(blank=True, choices=[('積極的で好奇心旺盛', '積極的で好奇心旺盛'), ('普通だけど刺激が欲しい', '普通だけど刺激が欲しい'), ('普通だけど相性は大事', '普通だけど相性は大事')], max_length=20, null=True)),
                ('sake', models.CharField(blank=True, choices=[('たしなむ程度', 'たしなむ程度'), ('飲めない', '飲めない'), ('飲めないが場は好き', '飲めないが場は好き')], max_length=20, null=True)),
                ('process_before_meeting', models.CharField(blank=True, choices=[('まずは会ってみたい', 'まずは会ってみたい'), ('気が合いそうなら会ってみたい', '気が合いそうなら会ってみたい')], max_length=20, null=True)),
                ('first_date_cost', models.CharField(blank=True, choices=[('相手と相談して決める', '相手と相談して決める')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PCMAX',
                'verbose_name_plural': 'PCMAX',
                'db_table': 'pcmax',
                'managed': True,
            },
        ),
    ]
