# Generated by Django 3.2.5 on 2024-07-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='happymail',
            options={'managed': True, 'verbose_name': 'ハッピーメール', 'verbose_name_plural': 'ハッピーメール'},
        ),
        migrations.AlterModelOptions(
            name='pcmax',
            options={'managed': True, 'verbose_name': 'PCMAX', 'verbose_name_plural': 'PCMAX'},
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='body_shape',
            field=models.CharField(choices=[('普通', '普通'), ('未設定', '未設定'), ('スリム', 'スリム'), ('やや細め', 'やや細め'), ('グラマー', 'グラマー'), ('ややぽっちゃり', 'ややぽっちゃり'), ('太め', '太め')], max_length=20),
        ),
    ]
