# Generated by Django 5.1 on 2024-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='another_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Registration_subscribe_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
