# Generated by Django 3.2.5 on 2024-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240710_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmax',
            name='body_shape',
            field=models.CharField(choices=[('普通', '普通'), ('未設定', '未設定'), ('スリム', 'スリム'), ('やや細め', 'やや細め'), ('グラマー', 'グラマー'), ('ややぽっちゃり', 'ややぽっちゃり'), ('太め', '太め')], max_length=20, null=True),
        ),
    ]
