# Generated by Django 5.1 on 2024-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_additional_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Registration_subscribe_date',
            field=models.DateField(blank=True, null=True, verbose_name='課金日'),
        ),
    ]
