# Generated by Django 5.1 on 2024-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lifted_account_number',
            field=models.BooleanField(default=False, verbose_name='アカウント数制限16'),
        ),
    ]
