# Generated by Django 5.1 on 2024-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_lifted_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_account',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmailアドレス'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmail_account_password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gmailアプリパスワード'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lifted_account_number',
            field=models.BooleanField(default=False, verbose_name='アカウント数制限解除(16)'),
        ),
    ]
