# Generated by Django 3.2.5 on 2024-07-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240710_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmax',
            name='return_foot_message',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='足跡返し'),
        ),
    ]
