# Generated by Django 5.1 on 2024-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_gmail_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='chara_image',
            field=models.ImageField(blank=True, null=True, upload_to='chara_images/'),
        ),
    ]
