# Generated by Django 3.2.5 on 2024-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pcmax_return_foot_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happymail',
            name='conditions_message',
            field=models.TextField(blank=True, null=True, verbose_name='2stメール'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='fst_message',
            field=models.TextField(blank=True, null=True, verbose_name='1stメール'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='login_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ログインID'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='post_contents',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板内容文'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='post_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='掲示板タイトル'),
        ),
        migrations.AlterField(
            model_name='happymail',
            name='return_foot_message',
            field=models.TextField(blank=True, null=True, verbose_name='足跡返し'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='condition_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='fst_mail',
            field=models.TextField(blank=True, null=True, verbose_name='1stメール'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='post_content',
            field=models.TextField(blank=True, null=True, verbose_name='掲示板内容文'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='post_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='掲示板タイトル'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='profession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='return_foot_message',
            field=models.TextField(blank=True, null=True, verbose_name='足跡返し'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='second_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='self_promotion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
