# Generated by Django 5.1 on 2024-09-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pcmax_activity_area_alter_pcmax_blood_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Registration_subscribe_date',
            new_name='registration_subscribe_date',
        ),
    ]
