# Generated by Django 5.1 on 2024-09-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_registration_subscribe_date_userprofile_registration_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happymail',
            name='post_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='掲示板タイトル'),
        ),
    ]
