# Generated by Django 5.1 on 2024-08-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_happymail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmax',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ'),
        ),
    ]
