# Generated by Django 5.1 on 2024-09-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_happymail_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmax',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
