# Generated by Django 5.1 on 2024-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pcmax_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmax',
            name='gmail_password',
            field=models.TextField(blank=True, null=True, verbose_name='Gmailパスワード'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmaliアドレス'),
        ),
    ]
