# Generated by Django 5.1 on 2024-10-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_pcmax_gmail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmax',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='profession',
            field=models.CharField(blank=True, null=True, verbose_name='職業'),
        ),
    ]
