# Generated by Django 5.1 on 2024-10-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_pcmax_date_of_birth_alter_pcmax_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recieve_mailaddress',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='受信用メールアドレス'),
        ),
    ]
