# Generated by Django 5.1 on 2024-10-07 05:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile_recieve_mailaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name': 'ユーザーオプション', 'verbose_name_plural': 'ユーザーオプション'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='h_schedule_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None, verbose_name='ハッピー予約時間'),
        ),
    ]
