# Generated by Django 5.1 on 2024-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_happymail_memo_pcmax_memo_alter_pcmax_car_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='happymail',
            name='activity_area',
            field=models.CharField(blank=True, choices=[('東京都', '東京都')], max_length=5, null=True, verbose_name='居住地'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='age',
            field=models.CharField(blank=True, choices=[('ナイショ', 'ナイショ'), ('18～19歳', '18～19歳'), ('20代前半', '20代前半'), ('20代半ば', '20代半ば'), ('20代後半', '20代後半')], max_length=6, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='birth_place',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='出身地'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('指定しない', '指定しない'), ('Ａ型', 'Ａ型'), ('Ｂ型', 'Ｂ型'), ('Ｏ型', 'Ｏ型'), ('ＡＢ型', 'ＡＢ型'), ('わからない', 'わからない'), ('ナイショ', 'ナイショ')], max_length=5, null=True, verbose_name='血液型'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='constellation',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='星座'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='cup',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='カップ'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='detail_activity_area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='詳細エリア'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='height',
            field=models.CharField(blank=True, choices=[('150～154', '150～154'), ('155～159', '155～159'), ('160～164', '160～164'), ('165～169', '165～169'), ('ナイショ', 'ナイショ')], max_length=10, null=True, verbose_name='身長'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='looks',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ルックス'),
        ),
        migrations.AddField(
            model_name='happymail',
            name='style',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='スタイル'),
        ),
    ]
