# Generated by Django 5.1 on 2024-10-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_happymail_brothers_and_sisters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ'),
        ),
    ]
