# Generated by Django 5.1 on 2024-10-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check_mail_pcmax',
            field=models.BooleanField(default=False, verbose_name='pcmax新着チェック'),
        ),
    ]
