# Generated by Django 5.1 on 2024-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_pcmax_annual_income_pcmax_birth_place_pcmax_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmax',
            name='car_ownership',
            field=models.CharField(blank=True, choices=[('ない', 'ない'), ('車がある', '車がある'), ('バイクがある', 'バイクがある'), ('車とバイク両方ある', '車とバイク両方ある')], max_length=20, null=True, verbose_name='車の所有'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='detail_activity_area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='活動エリア(詳細)'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='first_date_cost',
            field=models.CharField(blank=True, choices=[('未回答', '未回答'), ('自分が全部払う', '自分が全部払う'), ('自分が多めに払う', '自分が多めに払う'), ('割り勘', '割り勘'), ('お相手に全部払ってもらう', 'お相手に全部払ってもらう'), ('お相手に多めに払ってもらう', 'お相手に多めに払ってもらう'), ('持っている方が払う', '持っている方が払う'), ('相手と相談して決める', '相手と相談して決める')], max_length=20, null=True, verbose_name='初回デート費用'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='smoking',
            field=models.CharField(blank=True, choices=[('未選択', '未選択'), ('吸わない(喫煙は気にしない)', '吸わない(喫煙は気にしない)'), ('吸わない(喫煙は気になる)', '吸わない(喫煙は気になる)'), ('吸わない(喫煙は許せない)', '吸わない(喫煙は許せない)'), ('吸わない(喫煙は気にしない)', '吸わない(喫煙は気にしない)'), ('吸う（1日1箱くらい）', '吸う（1日1箱くらい）'), ('吸う（1日1箱以上）', '吸う（1日1箱以上）'), ('吸う（2～3日に1箱）', '吸う（2～3日に1箱）'), ('吸う（気が向いた時だけ）', '吸う（気が向いた時だけ）'), ('吸う（電子タバコ）', '吸う（電子タバコ）'), ('禁煙中', '禁煙中'), ('非喫煙者の前では吸わない', '非喫煙者の前では吸わない')], max_length=20, null=True, verbose_name='喫煙'),
        ),
    ]
