# Generated by Django 5.1 on 2024-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_pcmax_car_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmax',
            name='ecchiness_level',
            field=models.CharField(blank=True, choices=[('積極的で経験豊か', '積極的で経験豊か'), ('積極的で好奇心旺盛', '積極的で好奇心旺盛'), ('普通だし気持ちが大切', '普通だし気持ちが大切'), ('奥手だけど興味あり', '奥手だけど興味あり'), ('普通だけど刺激が欲しい', '普通だけど刺激が欲しい'), ('普通だけど相性は大事', '普通だけど相性は大事'), ('奥手だし苦手です', '奥手だし苦手です'), ('まだ未経験です', 'まだ未経験です'), ('奥手だし下ﾈﾀもNG', '奥手だし下ﾈﾀもNG')], max_length=20, null=True, verbose_name='エッチ度'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='sake',
            field=models.CharField(blank=True, choices=[('未回答', '未回答'), ('好き', '好き'), ('たしなむ程度', 'たしなむ程度'), ('相手に合わせたい', '相手に合わせたい'), ('飲めない', '飲めない'), ('飲めないが場は好き', '飲めないが場は好き')], max_length=20, null=True, verbose_name='お酒'),
        ),
    ]
