# Generated by Django 5.1 on 2024-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_pcmax_ecchiness_level_alter_pcmax_sake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='check_mail_happymail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='check_mail_pcmax',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='check_mail',
            field=models.BooleanField(default=False, verbose_name='新着チェック'),
        ),
    ]
