# Generated by Django 5.1 on 2024-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_userprofile_p_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happymail',
            name='intention_to_marry',
            field=models.CharField(blank=True, choices=[('すぐにでもしたい', 'すぐにでもしたい'), ('2～3年のうちに', '2～3年のうちに'), ('良い人がいればしたい', '良い人がいればしたい'), ('わからない', 'わからない')], max_length=20, null=True, verbose_name='結婚に対する意思'),
        ),
    ]
