# Generated by Django 5.1 on 2024-12-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_happymail_intention_to_marry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名前')),
                ('login_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ログインID')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='パスワード')),
                ('fst_message', models.TextField(blank=True, null=True, verbose_name='1stメール')),
                ('return_foot_message', models.TextField(blank=True, null=True, verbose_name='足跡返し')),
                ('conditions_message', models.TextField(blank=True, null=True, verbose_name='2stメール')),
                ('post_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='掲示板タイトル')),
                ('post_contents', models.TextField(blank=True, null=True, verbose_name='掲示板内容文')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jmail',
                'verbose_name_plural': 'Jmail',
                'db_table': 'jmail',
                'managed': True,
            },
        ),
    ]
