# Generated by Django 5.1 on 2024-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_jmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='memo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='メモ'),
        ),
    ]
