# Generated by Django 5.1.4 on 2025-01-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_jmail_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jmail',
            name='chara_image',
            field=models.ImageField(blank=True, null=True, upload_to='chara_images/', verbose_name='送付画像'),
        ),
        migrations.AlterField(
            model_name='pcmax',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmailアドレス'),
        ),
        migrations.CreateModel(
            name='Ikukuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名前')),
                ('login_mailaddress', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='パスワード')),
                ('fst_message', models.TextField(blank=True, null=True, verbose_name='1stメール')),
                ('sedond_message', models.TextField(blank=True, null=True, verbose_name='2stメール')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('memo', models.CharField(blank=True, max_length=30, null=True, verbose_name='メモ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ikukuru',
                'verbose_name_plural': 'Ikukuru',
                'db_table': 'Ikukuru',
                'managed': True,
            },
        ),
    ]
