# Generated by Django 5.1.4 on 2025-01-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_jmail_chara_image_alter_pcmax_mail_address_ikukuru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ikukuru',
            old_name='sedond_message',
            new_name='second_message',
        ),
    ]
